//! The `.aion` chain: read the previous payload, append a signed version, and
//! verify before anyone sees the result.

use anyhow::{bail, Context, Result};
use std::path::{Path, PathBuf};

use aion_context::crypto::SigningKey;
use aion_context::key_registry::KeyRegistry;
use aion_context::keystore::KeyStore;
use aion_context::operations::{self, CommitOptions, InitOptions, VerificationReport};
use aion_context::types::AuthorId;

use crate::bundle::Bundle;
use crate::canon;

pub struct Signer {
    pub author: u64,
    pub key: u64,
    /// Explicit keystore directory. CI has no OS keyring, so the file-backed
    /// store is the path that actually runs in the action.
    pub keystore_dir: Option<PathBuf>,
    /// Hex-encoded Ed25519 seed, normally from a CI secret.
    ///
    /// The file keystore encrypts with a machine-derived key, so a key file
    /// copied to a runner cannot be decrypted there. The seed travels instead,
    /// and never touches the runner's disk.
    pub secret_hex: Option<String>,
}

impl Signer {
    fn keystore(&self) -> KeyStore {
        match &self.keystore_dir {
            Some(dir) => KeyStore::with_storage_dir(dir.clone()),
            None => KeyStore::new(),
        }
    }

    pub fn load(&self) -> Result<SigningKey> {
        if let Some(secret) = &self.secret_hex {
            let bytes =
                canon::from_hex(secret.trim()).context("signing secret is not hex-encoded")?;
            anyhow::ensure!(
                bytes.len() == 32,
                "signing secret must be 32 bytes (64 hex chars), got {}",
                bytes.len()
            );
            return SigningKey::from_bytes(&bytes)
                .map_err(|e| anyhow::anyhow!("signing secret is not a valid Ed25519 seed: {e}"));
        }
        let id = AuthorId::new(self.key);
        match self.keystore().load_signing_key(id) {
            Ok(key) => Ok(key),
            // `KeyStore::new()` prefers the OS keyring where one is reachable;
            // a key generated by the file store then looks missing.
            Err(keyring_error) if self.keystore_dir.is_none() => KeyStore::file_based()
                .load_signing_key(id)
                .with_context(|| {
                    format!(
                        "signing key {} is in neither the keyring ({keyring_error}) nor ~/.aion/keys",
                        self.key
                    )
                }),
            Err(e) => Err(anyhow::anyhow!("signing key {} is unusable: {e}", self.key)),
        }
    }
}

/// Create a signing key and the registry that pins it, both file-backed, and
/// return the hex seed a CI secret must hold.
pub fn keygen(
    key: u64,
    author: u64,
    keystore_dir: Option<&Path>,
    registry_path: &Path,
) -> Result<String> {
    let store = match keystore_dir {
        Some(dir) => KeyStore::with_storage_dir(dir.to_path_buf()),
        None => KeyStore::file_based(),
    };
    let (signing, verifying) = store
        .generate_keypair(AuthorId::new(key))
        .map_err(|e| anyhow::anyhow!("generating key {key}: {e}"))?;

    let mut registry = if registry_path.exists() {
        load_registry(registry_path)?
    } else {
        KeyRegistry::new()
    };
    registry
        .register_author(AuthorId::new(author), verifying, verifying, 1)
        .map_err(|e| anyhow::anyhow!("registering author {author}: {e}"))?;
    let json = registry
        .to_trusted_json()
        .map_err(|e| anyhow::anyhow!("serializing registry: {e}"))?;
    if let Some(parent) = registry_path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(registry_path, json)?;
    Ok(canon::hex(signing.to_bytes()))
}

/// Reveal an existing key's seed for a CI secret, refusing if it is not the key
/// the committed registry pins. Regenerating instead would orphan the registry
/// and break the chain's continuity.
pub fn reveal_secret(
    key: u64,
    author: u64,
    keystore_dir: Option<PathBuf>,
    registry_path: &Path,
) -> Result<String> {
    let signer = Signer {
        author,
        key,
        keystore_dir,
        secret_hex: None,
    };
    let signing = signer.load()?;
    let public = signing.verifying_key().to_bytes();
    let registry = load_registry(registry_path)?;
    anyhow::ensure!(
        registry
            .epochs_for(AuthorId::new(author))
            .iter()
            .any(|epoch| epoch.public_key == public),
        "key {key} does not match any epoch pinned for author {author} in {} — \
         signing with it would produce a chain that fails verification",
        registry_path.display()
    );
    Ok(canon::hex(signing.to_bytes()))
}

pub fn load_registry(path: &Path) -> Result<KeyRegistry> {
    let text = std::fs::read_to_string(path)
        .with_context(|| format!("reading registry {}", path.display()))?;
    KeyRegistry::from_trusted_json(&text)
        .map_err(|e| anyhow::anyhow!("registry {} is not usable: {e}", path.display()))
}

/// The payload of the chain's current version, if the chain exists.
pub fn previous_bundle(path: &Path) -> Result<Option<Bundle>> {
    if !path.exists() {
        return Ok(None);
    }
    let payload = operations::show_current_rules(path)
        .with_context(|| format!("reading current payload from {}", path.display()))?;
    Bundle::parse(&payload).map(Some)
}

/// Append a signed version (or create the chain), then verify it.
pub fn commit(
    path: &Path,
    bundle: &Bundle,
    message: &str,
    signer: &Signer,
    registry: &KeyRegistry,
) -> Result<u64> {
    let payload = bundle.to_bytes()?;
    let timestamp = bundle.pinned_timestamp();
    let signing_key = signer.load()?;

    let version = if path.exists() {
        operations::commit_version(
            path,
            &payload,
            &CommitOptions {
                author_id: AuthorId::new(signer.author),
                signing_key: &signing_key,
                message,
                timestamp,
            },
            registry,
        )
        .map_err(|e| anyhow::anyhow!("commit rejected: {e}"))?
        .version
        .as_u64()
    } else {
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                std::fs::create_dir_all(parent)?;
            }
        }
        operations::init_file(
            path,
            &payload,
            &InitOptions {
                author_id: AuthorId::new(signer.author),
                signing_key: &signing_key,
                message,
                timestamp,
            },
        )
        .map_err(|e| anyhow::anyhow!("genesis rejected: {e}"))?
        .version
        .as_u64()
    };

    let report = verify(path, registry)?;
    if !report.is_valid {
        bail!(
            "chain failed verification immediately after commit: {:?}",
            report.errors
        );
    }
    Ok(version)
}

pub fn verify(path: &Path, registry: &KeyRegistry) -> Result<VerificationReport> {
    operations::verify_file(path, registry)
        .map_err(|e| anyhow::anyhow!("verification of {} failed: {e}", path.display()))
}

/// The chain proves the payload; `data/` is what a human reads in the diff.
/// They must agree, so this re-derives the digests from disk rather than
/// trusting that the run that wrote them was the run that signed them.
pub fn data_matches(bundle: &Bundle, data_dir: &Path) -> Result<Vec<String>> {
    let mut mismatches = Vec::new();
    for (number, record) in &bundle.parts {
        let path = data_dir.join(format!("part-{number}.json"));
        if !path.exists() {
            mismatches.push(format!("{} is missing", path.display()));
            continue;
        }
        let value = canon::canonicalize(&std::fs::read(&path)?)?;
        let digest = canon::digest_value(&value)?;
        if digest != record.sha256 {
            mismatches.push(format!(
                "{} digest {digest} does not match the signed {}",
                path.display(),
                record.sha256
            ));
        }
    }
    Ok(mismatches)
}
